services:
  ui:
    image: python:3.12-slim
    container_name: tlsaudithub-ui
    volumes:
      - ./ui:/app
    working_dir: /app
    command: >
      sh -c "python /app/secure_server.py"
    ports:
      - "5173:5173"
    depends_on:
      - api

  api:
    image: python:3.12-slim
    container_name: tlsaudithub-api
    env_file:
    - .env
    environment:
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
      NO_PROXY: ${NO_PROXY}
    volumes:
      - ./api:/app
      - ./app:/app/shared
    working_dir: /app
    command: >
      sh -c "pip install -r /app/requirements.txt &&
             uvicorn main:app --host 0.0.0.0 --port 8000 --no-server-header"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

  worker:
    image: python:3.12-slim
    container_name: tlsaudithub-worker
    environment:
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
      NO_PROXY: ${NO_PROXY}
    volumes:
      - ./worker:/app
      - ./app:/app/shared
    working_dir: /app
    command: >
      sh -c "pip install sslyze celery redis psycopg2-binary sqlalchemy dnspython python-whois &&
             celery -A worker worker --loglevel=info"
    depends_on:
      - redis
      - postgres

  scheduler:
    image: python:3.12-slim
    container_name: tlsaudithub-scheduler
    environment:
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
      NO_PROXY: ${NO_PROXY}
    volumes:
      - ./worker:/app
      - ./app:/app/shared
    working_dir: /app
    command: >
      sh -c "pip install sslyze celery redis psycopg2-binary sqlalchemy dnspython python-whois &&
             celery -A worker beat --loglevel=info"
    depends_on:
      - redis

  postgres:
    image: postgres:16
    container_name: tlsaudithub-postgres
    environment:
      POSTGRES_DB: sslyze
      POSTGRES_USER: sslyze
      POSTGRES_PASSWORD: sslyze
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: tlsaudithub-redis
    volumes:
      - ./data/redis:/data
